eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8767

feign:
  client:
    config:
      default:
        connectTimeout: 5000   # Thời gian chờ kết nối (ms)
        readTimeout: 5000      # Thời gian chờ đọc dữ liệu (ms)
        loggerLevel: FULL      # Log chi tiết request & response

spring:
  servlet:
    # Giới hạn kích thước file tải lên
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      # Giới hạn tổng số lượng file tải lên
      file-size-threshold: 2MB
  aop:
    auto: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.20.99:1433;databaseName=PRODUCTION;encrypt=false;trustServerCertificate=true;
    username: sa
    password: dev*2304
  data:
    mongodb:
      uri: mongodb://localhost:27017/AlvaDB

swagger:
  enabled: true

logging:
  level:
    org.springframework: ERROR